Repository add-mores/backend, pull requests merged in 2025-05, with the labels that each got.

#7 0.1/feat medicapi jiwon [의약품 정보와 병원 코드를 이용한 병원 진료 과목을 불러오는 api 호출 코드 작성]
  code/medic/call_hospital_api.py
  code/medic/call_medicine_api.py
  code/medic/clean_medicine.py
  postgres/db_code/jiwon_dis_import.py
Labels: enhancement

#12 0.1/hospital hyun [입력 주소 기반 가까운 병원 추천 Streamlit 구현]
  code/hospital/call_hospital_api.py
  code/hospital/hospital_kakao_api.py
  pages/3_hospital.py
  pdm.lock
  pyproject.toml
Labels: enhancement

#15 0.1/hospital hyun [완전 일치 기반 필터링]
  pages/2_hospital.py
Labels: bug

#14 0.1/feat_disease_Proto_jacob
  main.py
  pages/1_disease.py
  utils.py
Labels: enhancement

#18 0.1/hospital hyun
  code/hospital/failed_hospital_kakao_api.py
  code/hospital/hospital_kakao_api.py
  pages/2_hospital.py
  pdm.lock
  pyproject.toml
Labels: enhancement

#21 0.1/hospital hyun [API 호출 문제 해결 + DB 연결]
  code/hospital/failed_hospital_kakao_api.py
  code/hospital/hospital_kakao_api.py
  pages/2_hospital.py
Labels: bug, enhancement

#20 0.1/disease jacob[약식 TF-IDF 적용]
  pages/1_disease.py
  pages/_utils.py
  utils.py
Labels: enhancement

#10 0.1/stereamlit [Set Streamlit]
  .DS_Store
  .gitignore
  code/hospital/call_hospital_api.py
  code/hospital/hospital_kakao_api.py
  code/streamlit/_utils.py
  main.py
  pages/.gitkeeps
  pages/1_disease.py
  pages/2_hospital.py
  pages/2_medicine.py
  pages/3_medicine.py
  pdm.lock
  pyproject.toml
Labels: enhancement

#30 0.3/feat hospi hyun [병원 호출 및 현재 위치 위경도 계산 API]
  app/api/hospital_api.py
  app/main.py
  pdm.lock
Labels: enhancement
